services:
  - type: web
    name: smartbank
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: MYSQL_URL
        sync: false
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
